incremental: true

cloud:
    url: https://127.0.0.1:8010
    support: https://127.0.0.1:8010/go/profile_support

language_base:
    cs: 'http://0.0.0.0:4000'
    de: 'http://0.0.0.0:4000'
    en: 'http://0.0.0.0:4000'
    es: 'http://0.0.0.0:4000'
    fr: 'http://0.0.0.0:4000'
    he: 'http://0.0.0.0:4000'
    hr: 'http://0.0.0.0:4000'
    it: 'http://0.0.0.0:4000'
    nl: 'http://0.0.0.0:4000'
    pl: 'http://0.0.0.0:4000'
    pt: 'http://0.0.0.0:4000'
    pt_BR: 'http://0.0.0.0:4000'
    ru: 'http://0.0.0.0:4000'
    sk: 'http://0.0.0.0:4000'
    sv: 'http://0.0.0.0:4000'
    uk: 'http://0.0.0.0:4000'
    zh_Hans: 'http://0.0.0.0:4000'
    zh_Hant: 'http://0.0.0.0:4000'

custom_domain:
    zh_Hant: false
