<?php

/**
 * Redirects visitors from https://www.kimai.org/ to their preferred language,
 * based on the browser's Accept-Language header.
 *
 * The list of available languages is generated by Jekyll from _config.yml:
 *
 * languages:
 *     - cs
 *     - de
 *     - en
 *     - ...
 */

$availableLanguages = [

    'ca',
    'cs',
    'de',
    'en',
    'es',
    'fr',
    'he',
    'hr',
    'it',
    'nl',
    'pl',
    'pt',
    'pt_BR',
    'ru',
    'sk',
    'sv',
    'ta',
    'uk',
    'zh_Hans',
    'zh_Hant',
];

$fallbackLanguage = 'en';

/**
 * Normalizes browser locale codes to the locale format used by the website.
 *
 * Browsers usually send locales with hyphens, for example:
 *   pt-BR
 *   zh-Hans
 *
 * Kimai uses underscore-based paths, for example:
 *   /pt_BR/
 *   /zh_Hans/
 */
function normalizeLocale(string $locale): string
{
    $locale = trim($locale);

    if ($locale === '') {
        return '';
    }

    $locale = str_replace('-', '_', $locale);

    /**
     * Explicit aliases for locales where the browser language does not
     * necessarily match the website path one-to-one.
     */
    $aliases = [
        // Portuguese
        'pt_BR' => 'pt_BR',
        'pt_br' => 'pt_BR',

        // Chinese simplified
        'zh' => 'zh_Hans',
        'zh_CN' => 'zh_Hans',
        'zh_cn' => 'zh_Hans',
        'zh_SG' => 'zh_Hans',
        'zh_sg' => 'zh_Hans',
        'zh_Hans' => 'zh_Hans',
        'zh_hans' => 'zh_Hans',

        // Chinese traditional
        'zh_TW' => 'zh_Hant',
        'zh_tw' => 'zh_Hant',
        'zh_HK' => 'zh_Hant',
        'zh_hk' => 'zh_Hant',
        'zh_MO' => 'zh_Hant',
        'zh_mo' => 'zh_Hant',
        'zh_Hant' => 'zh_Hant',
        'zh_hant' => 'zh_Hant',
    ];

    return $aliases[$locale] ?? $locale;
}

/**
 * Parses the Accept-Language header.
 *
 * Example:
 *   de-AT,de;q=0.9,en-US;q=0.8,en;q=0.7
 *
 * Result:
 *   [
 *       ['locale' => 'de_AT', 'quality' => 1.0],
 *       ['locale' => 'de',    'quality' => 0.9],
 *       ['locale' => 'en_US', 'quality' => 0.8],
 *       ['locale' => 'en',    'quality' => 0.7],
 *   ]
 */
function parseAcceptLanguageHeader(string $header): array
{
    $languages = [];

    foreach (explode(',', $header) as $part) {
        $part = trim($part);

        if ($part === '') {
            continue;
        }

        $pieces = array_map('trim', explode(';', $part));

        $locale = normalizeLocale($pieces[0] ?? '');

        if ($locale === '' || $locale === '*') {
            continue;
        }

        $quality = 1.0;

        foreach ($pieces as $piece) {
            if (preg_match('/^q=([01](?:\.\d{0,3})?)$/', $piece, $match)) {
                $quality = (float) $match[1];
                break;
            }
        }

        if ($quality <= 0) {
            continue;
        }

        $languages[] = [
            'locale' => $locale,
            'quality' => $quality,
        ];
    }

    usort($languages, static function (array $a, array $b): int {
        return $b['quality'] <=> $a['quality'];
    });

    return $languages;
}

/**
 * Finds the best matching website language.
 *
 * Matching order:
 *
 * 1. Exact match:
 *      pt_BR → pt_BR
 *
 * 2. Base language fallback:
 *      de_AT → de
 *      fr_CA → fr
 *
 * 3. Final fallback:
 *      en
 */
function detectPreferredLanguage(array $availableLanguages, string $fallbackLanguage): string
{
    $header = $_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? '';

    if (!is_string($header) || trim($header) === '') {
        return $fallbackLanguage;
    }

    $acceptedLanguages = parseAcceptLanguageHeader($header);

    foreach ($acceptedLanguages as $acceptedLanguage) {
        $locale = $acceptedLanguage['locale'];

        if (in_array($locale, $availableLanguages, true)) {
            return $locale;
        }

        $baseLocale = explode('_', $locale)[0];

        if (in_array($baseLocale, $availableLanguages, true)) {
            return $baseLocale;
        }
    }

    return $fallbackLanguage;
}

$language = detectPreferredLanguage($availableLanguages, $fallbackLanguage);

/**
 * Defensive fallback, in case the configured fallback language was removed
 * accidentally from _config.yml.
 */
if (!in_array($language, $availableLanguages, true)) {
    $language = 'en';
}

$target = '/' . rawurlencode($language) . '/';

/**
 * Do not use 301 here.
 *
 * Browser language preferences can change, and permanent redirects can get
 * cached very aggressively.
 */
header('Vary: Accept-Language');
header('Cache-Control: private, no-cache, no-store, max-age=0');
header('Location: ' . $target, true, 302);
exit;
