require 'uri'

module Jekyll
  # Rewrites links in rendered changelog HTML for consumption outside the website:
  # - root-relative hrefs (as generated by {% link %}) become absolute URLs
  # - UTM parameters are appended to internal hrefs, keeping anchors and existing query strings intact
  module ChangelogLinksFilter
    def changelog_links(input, utm_source, utm_medium)
      site_url = @context.registers[:site].config['url']
      utm = "utm_source=#{utm_source}&utm_medium=#{utm_medium}"

      input.gsub(/href="([^"]+)"/) do
        href = Regexp.last_match(1)
        href = "#{site_url}#{href}" if href.start_with?('/')

        uri = URI.parse(href) rescue nil
        next "href=\"#{href}\"" if uri.nil? || uri.scheme.nil? || !href.start_with?(site_url)

        uri.query = [uri.query, utm].compact.join('&')
        "href=\"#{uri}\""
      end
    end
  end
end

Liquid::Template.register_filter(Jekyll::ChangelogLinksFilter)
