<?php

/**
 * Updates _data/customer-map.yml (used by /en/map) from the raw customer numbers per country.
 *
 * The raw numbers are NOT published: the CSV files are listed in .gitignore and the YAML file
 * only contains the reached level (1, 10 or 100) per country and dataset.
 *
 * Input files (two columns, with header line): ISO 3166-1 alpha-2 code, number of customers
 *   src/data/countries-cloud.csv
 *   src/data/countries-onpremise.csv
 *
 * The dataset "all" is calculated from the sum of all datasets.
 *
 * Usage: php scripts/update-customer-map.php
 */

$rootDir = realpath(__DIR__ . '/..');

// the minimum number of customers for each level
$levels = [1, 10, 100];

// dataset name => CSV file
$datasets = [
    'cloud' => 'src/data/countries-cloud.csv',
    'onpremise' => 'src/data/countries-onpremise.csv',
];

$outputFile = '_data/customer-map.yml';

// used to warn about countries that can not be shown
$mapFile = 'images/world-map-miller.svg';

// ---------------------------------------------------------------------------------------------------

$missing = [];
foreach ($datasets as $file) {
    if (!is_readable($rootDir . '/' . $file)) {
        $missing[] = $file;
    }
}

if (count($missing) > 0) {
    foreach ($missing as $file) {
        echo "Warning: missing file $file" . PHP_EOL;
    }
    echo "Warning: $outputFile was not updated" . PHP_EOL;
    exit(1);
}

$counts = [];
foreach ($datasets as $dataset => $file) {
    $handle = fopen($rootDir . '/' . $file, 'r');
    $line = 0;
    while (($row = fgetcsv($handle, escape: '')) !== false) {
        $line++;
        if ($row === [null] || $row === ['']) {
            continue;
        }

        $iso = strtoupper(trim($row[0] ?? ''));
        $count = trim($row[1] ?? '');

        // header line
        if ($line === 1 && !ctype_digit($count)) {
            continue;
        }

        if (!preg_match('/^[A-Z]{2}$/', $iso) || !ctype_digit($count)) {
            echo "Warning: skipping invalid line $line in $file: " . implode(',', $row) . PHP_EOL;
            continue;
        }

        $counts[$iso][$dataset] = ($counts[$iso][$dataset] ?? 0) + (int) $count;
    }
    fclose($handle);
}

// the highest level reached by a number, null if none
$levelOf = function (int $count) use ($levels): ?int {
    $result = null;
    foreach ($levels as $level) {
        if ($count >= $level) {
            $result = $level;
        }
    }

    return $result;
};

$countries = [];
foreach ($counts as $iso => $values) {
    $country = [];
    $all = $levelOf(array_sum($values));
    if ($all !== null) {
        $country['all'] = $all;
    }
    foreach (array_keys($datasets) as $dataset) {
        $level = $levelOf($values[$dataset] ?? 0);
        if ($level !== null) {
            $country[$dataset] = $level;
        }
    }
    if (count($country) > 0) {
        $countries[$iso] = $country;
    }
}
ksort($countries);

// only list datasets that have values, "all" is only useful when there is more than one
$usedDatasets = array_values(array_filter(array_keys($datasets), function (string $dataset) use ($countries): bool {
    foreach ($countries as $country) {
        if (isset($country[$dataset])) {
            return true;
        }
    }

    return false;
}));
if (count($usedDatasets) > 1) {
    array_unshift($usedDatasets, 'all');
} else {
    foreach ($countries as $iso => $country) {
        unset($countries[$iso]['all']);
    }
}

$mapCountries = [];
if (preg_match_all('/data-iso="([A-Z]{2})"/', (string) @file_get_contents($rootDir . '/' . $mapFile), $matches)) {
    $mapCountries = array_flip($matches[1]);
}
foreach (array_keys($countries) as $iso) {
    if (count($mapCountries) > 0 && !isset($mapCountries[$iso])) {
        echo "Warning: country $iso is not part of the world map" . PHP_EOL;
    }
}

$yaml = [
    '# Generated by scripts/update-customer-map.php - do not edit manually.',
    '#',
    '# Countries with Kimai customers, shown on the world map (see images/world-map-*.svg).',
    '#',
    '# levels:    the minimum number of customers for each level, in ascending order',
    '# datasets:  the values that can be shown on the map, the first one is the default view',
    '#            "all" is calculated from the sum of all other datasets',
    '# countries: key = ISO 3166-1 alpha-2 code (same as data-iso in the SVG)',
    '#            value per dataset = the highest reached level',
    '#            countries or datasets that are not listed mean "no customers / unknown"',
    '#            keys are quoted, otherwise YAML reads "NO" (Norway) as false',
    '',
    'levels: [' . implode(', ', $levels) . ']',
    '',
    'datasets:',
];
foreach ($usedDatasets as $dataset) {
    $yaml[] = '  - ' . $dataset;
}
$yaml[] = '';
$yaml[] = 'countries:';
foreach ($countries as $iso => $country) {
    $yaml[] = '  "' . $iso . '":';
    foreach ($country as $dataset => $level) {
        $yaml[] = '    ' . $dataset . ': ' . $level;
    }
}

file_put_contents($rootDir . '/' . $outputFile, implode(PHP_EOL, $yaml) . PHP_EOL);

echo "Wrote $outputFile (" . count($countries) . " countries, datasets: " . implode(', ', $usedDatasets) . ")" . PHP_EOL;

// totals are only printed, they are never written to the YAML file
$total = 0;
foreach (array_keys($datasets) as $dataset) {
    $datasetTotal = array_sum(array_column($counts, $dataset));
    $total += $datasetTotal;
    echo "Customers $dataset: $datasetTotal" . PHP_EOL;
}
echo "Customers total: $total" . PHP_EOL;
